import PDFDocument from 'pdfkit'
import type { MappedAudit, MappedSubscription } from '../utils/mappers'

const CURRENCY_SYMBOLS: Record<string, string> = {
  NGN: 'NGN ',
  USD: '$',
  GBP: '£',
}

function formatAmount(amount: number, currency: string): string {
  const symbol = CURRENCY_SYMBOLS[currency] || currency
  return `${symbol}${amount.toLocaleString('en-NG', { maximumFractionDigits: 2 })}`
}

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-NG', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

/**
 * Renders a savings audit report as a PDF buffer.
 * Called once during processAudit(), after analysis completes —
 * the result is uploaded to storage and reused for every download,
 * rather than regenerated per request.
 */
export function generateAuditReportPdf(
  audit: MappedAudit,
  subscriptions: MappedSubscription[]
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 })
    const chunks: Buffer[] = []

    doc.on('data', (chunk) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    // Header
    doc
      .fontSize(20)
      .fillColor('#111827')
      .text('Subscription Audit Report', { align: 'left' })
    doc
      .fontSize(10)
      .fillColor('#6b7280')
      .text(`Generated ${formatDate(audit.createdAt)}`, { align: 'left' })
    doc.moveDown(1.5)

    // Summary stats
    doc.fontSize(12).fillColor('#111827').text('Summary', { underline: true })
    doc.moveDown(0.5)

    const summaryRows: [string, string][] = [
      ['Total subscriptions found', String(audit.totalSubscriptions)],
      ['Total monthly spend', formatAmount(audit.totalMonthlySpend, 'NGN')],
      ['Potential monthly savings', formatAmount(audit.potentialSavings, 'NGN')],
      ['Duplicate groups found', String(audit.duplicates.length)],
      ['Unused subscriptions', String(audit.unusedCount)],
    ]

    summaryRows.forEach(([label, value]) => {
      doc
        .fontSize(10)
        .fillColor('#374151')
        .text(label, { continued: true, width: 300 })
        .fillColor('#111827')
        .text(value, { align: 'right' })
    })

    doc.moveDown(1.5)

    // Duplicates section
    if (audit.duplicates.length > 0) {
      doc.fontSize(12).fillColor('#111827').text('Duplicate Subscriptions', { underline: true })
      doc.moveDown(0.5)

      audit.duplicates.forEach((group, i) => {
        doc.fontSize(10).fillColor('#991b1b').text(`Group ${i + 1}:`)
        group.forEach((sub) => {
          doc
            .fontSize(9)
            .fillColor('#374151')
            .text(
              `  • ${sub.name} — ${formatAmount(sub.amount, sub.currency)}/${sub.frequency}`
            )
        })
        doc.moveDown(0.3)
      })

      doc.moveDown(1)
    }

    // Full subscription list
    doc.fontSize(12).fillColor('#111827').text('All Subscriptions', { underline: true })
    doc.moveDown(0.5)

    if (subscriptions.length === 0) {
      doc.fontSize(10).fillColor('#6b7280').text('No subscriptions found.')
    } else {
      subscriptions.forEach((sub) => {
        doc
          .fontSize(9)
          .fillColor('#111827')
          .text(sub.name, { continued: true, width: 250 })
          .fillColor('#6b7280')
          .text(`  ${sub.category}  ·  ${sub.active ? 'active' : 'inactive'}`, {
            continued: true,
          })
          .fillColor('#111827')
          .text(`  ${formatAmount(sub.amount, sub.currency)}/${sub.frequency}`, {
            align: 'right',
          })
      })
    }

    doc.moveDown(2)
    doc
      .fontSize(8)
      .fillColor('#9ca3af')
      .text('Generated by SAT — Subscription Audit Tool', { align: 'center' })

    doc.end()
  })
}
